name: Build Release APK

on:
  push:
    branches:
      - xposed-module
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AmapPurify-release
          path: app/build/outputs/apk/release/
          retention-days: 30
